version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AWS-Slack-Tutorial-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1195ghv8pjng4"
s3_prefix = "AWS-Slack-Tutorial-pipeline"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
