AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS-Slack-Tutorial

  Sample SAM Template for AWS-Slack-Tutorial

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
      - SSMParameterReadPolicy:
          ParameterName:
            slack-api
      Layers:
        - !Ref MyLambdaLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.cloudformation
              detail-type:
                - CloudFormation Stack Status Change

  MyLambdaLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
          LayerName: MyLambdaLayer
          Description: python dependencies
          ContentUri: lambda-layer/my-lambda-layer.zip
          CompatibleRuntimes:
              - python3.8
              - python3.7
          RetentionPolicy: Retain  # can use previous versions in lambda functions

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  MyLambdaLayerARN:
      Value: !Ref MyLambdaLayer
      Description: MyLambdaLayer ARN
      Export:
          Name: !Sub "${AWS::StackName}-MyLambdaLayer"
